# Copyright (c) 2026 ByteDance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generated bash/curl client against the native HTTP app; synthetic grading only."""

import io
import json
import os
import shutil
import socket
import subprocess
import tarfile
import threading
import time
from contextlib import contextmanager
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from types import SimpleNamespace

import pytest
import requests
import uvicorn

from sforge.harness import judge_server
from sforge.harness.config import SForgeConfig
from sforge.harness.evolve_scripts import generate_submit_script
from sforge.harness.grading import EvalDetail, EvalReport


@pytest.fixture
def judge(tmp_path, monkeypatch):
    for command in ("bash", "curl", "jq", "tar"):
        if not shutil.which(command):
            pytest.skip(f"Generated client requires {command}")
    states = []

    class TestState(judge_server.JudgeState):
        def load_tasks(self):
            self.tasks = {"example": SimpleNamespace(judge=SimpleNamespace(
                selection="score_first", score_direction="maximize"))}
            states.append(self)

    def grade(**kwargs):
        with tarfile.open(fileobj=io.BytesIO(kwargs["archive"]), mode="r:gz") as archive:
            assert "./answer.txt" in archive.getnames()
        return EvalReport(
            "example", kwargs["submission_id"], total_tests=1, passed=1,
            pass_rate=1.0, score=7, summary="synthetic result",
            details=[EvalDetail("check", "PASSED", "public diagnostic", score=7)],
        )

    monkeypatch.setattr(judge_server, "JudgeState", TestState)
    monkeypatch.setattr(judge_server, "create_backend_from_config",
                        lambda config: SimpleNamespace(backend_name="k8s"))
    monkeypatch.setattr(judge_server, "judge_submission", grade)
    app = judge_server.create_app(SForgeConfig(log_dir=tmp_path / "logs"))
    listener = socket.socket()
    listener.bind(("127.0.0.1", 0))
    url = f"http://127.0.0.1:{listener.getsockname()[1]}"
    server = uvicorn.Server(uvicorn.Config(app, log_level="error"))
    thread = threading.Thread(target=server.run, kwargs={"sockets": [listener]})
    thread.start()
    deadline = time.monotonic() + 10
    while not server.started:
        assert thread.is_alive() and time.monotonic() < deadline
        time.sleep(0.01)
    http = requests.Session()
    http.trust_env = False
    response = http.post(url + "/api/v1/register", json={
        "task_id": "example", "run_id": "run", "admin_secret": states[0].admin_secret,
        "submission_cooldown": 3600, "max_agent_submissions": 3,
    }, timeout=5)
    response.raise_for_status()
    token = response.json()["token"]
    patch = tmp_path / "patch"
    patch.mkdir()
    (patch / "answer.txt").write_text("synthetic answer")
    cache = tmp_path / "state.json"
    script = tmp_path / "sforge-submit"
    # Isolate the existing display cache; exercise all other generated bytes.
    script.write_text(generate_submit_script().replace("/tmp/sforge_state.json", str(cache)))
    subprocess.run(["bash", "-n", str(script)], check=True)

    def run(*args, judge_url=url, submit_token=token):
        env = dict(os.environ, SFORGE_JUDGE_URL=judge_url, SFORGE_TOKEN=submit_token,
                   SFORGE_PATCH_DIR=str(patch), NO_PROXY="127.0.0.1,localhost")
        return subprocess.run(["bash", str(script), *args], env=env,
                              capture_output=True, text=True, timeout=20)

    state = states[0]
    try:
        yield SimpleNamespace(run=run, state=state, token=token, http=http,
                              url=url, patch=patch, cache=cache)
    finally:
        state._reaper_stop.set()
        state._reaper_thread.join(timeout=5)
        server.should_exit = True
        thread.join(timeout=5)
        listener.close()
        http.close()
        assert not thread.is_alive() and not state._reaper_thread.is_alive()


def accepted_id(judge):
    entries = judge.state.get_run_history("run", "example")["entries"]
    assert len(entries) == 1
    return entries[0]["submission_id"]


def test_read_result_preserves_full_feedback_and_submission_opportunity(judge):
    submitted = judge.run()
    assert submitted.returncode == 0, submitted.stderr
    sid = accepted_id(judge)
    assert sid in submitted.stdout and "Score:       7" in submitted.stdout
    before = judge.state.resolve_token(judge.token)
    # Recovery must not inspect or archive the current working files.
    shutil.rmtree(judge.patch)
    for _ in range(2):
        recovered = judge.run("--result", sid, "--details")
        assert recovered.returncode == 0, recovered.stderr
        assert "Score:       7" in recovered.stdout
        assert "public diagnostic" in recovered.stdout
    assert judge.state.resolve_token(judge.token) == before
    assert len(json.loads(judge.cache.read_text())["submissions"]) == 1


@contextmanager
def drop_one_reply(judge, path):
    class Gateway(BaseHTTPRequestHandler):
        def forward(self):
            size = int(self.headers.get("Content-Length", "0"))
            response = judge.http.request(self.command, judge.url + self.path,
                data=self.rfile.read(size) if size else None,
                headers={"Content-Type": self.headers.get("Content-Type", "")}, timeout=5)
            matches = self.path == path or (path == "result" and self.path.startswith("/api/v1/result/"))
            if matches and not self.server.dropped:
                self.server.dropped = True
                self.close_connection = True
                self.connection.shutdown(socket.SHUT_RDWR)
                return
            self.send_response(response.status_code)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(response.content)))
            self.end_headers()
            self.wfile.write(response.content)

        do_POST = forward
        do_GET = forward

        def log_message(self, *args):
            pass

    gateway = ThreadingHTTPServer(("127.0.0.1", 0), Gateway)
    gateway.dropped = False
    thread = threading.Thread(target=gateway.serve_forever)
    thread.start()
    try:
        yield f"http://127.0.0.1:{gateway.server_port}", gateway
    finally:
        gateway.shutdown()
        gateway.server_close()
        thread.join(timeout=5)
        assert not thread.is_alive()


@pytest.mark.parametrize("path", ["/api/v1/submit", "result"])
def test_lost_reply_recovers_from_visible_history_without_resubmit(judge, path):
    with drop_one_reply(judge, path) as (url, gateway):
        submitted = judge.run(judge_url=url)
        assert gateway.dropped and submitted.returncode != 0
        if path == "/api/v1/submit":
            assert "acceptance is unknown" in submitted.stderr
        assert not judge.cache.exists()
        sid = accepted_id(judge)
        before = judge.state.resolve_token(judge.token)
        history = judge.run("--list", judge_url=url)
        assert history.returncode == 0 and sid in history.stdout
        recovered = judge.run("--result", sid, "--details", judge_url=url)
        assert recovered.returncode == 0 and "public diagnostic" in recovered.stdout
        assert judge.state.resolve_token(judge.token) == before


def test_token_history_errors_and_other_run_ids_are_not_empty_success(judge):
    assert judge.run().returncode == 0
    sid = accepted_id(judge)
    denied = judge.run("--list", submit_token="invalid")
    assert denied.returncode != 0 and "HTTP 401" in denied.stderr
    assert "Total submissions: 0" not in denied.stdout
    other = judge.state.register_session("example", "other")
    archive = io.BytesIO()
    with tarfile.open(fileobj=archive, mode="w:gz") as tar:
        content = b"synthetic answer"
        info = tarfile.TarInfo("./answer.txt")
        info.size = len(content)
        tar.addfile(info, io.BytesIO(content))
    auto = judge.state.submit("example", archive.getvalue(), "run", "auto-1")
    for token, requested in ((other, sid), (judge.token, "unknown"), (judge.token, auto)):
        denied = judge.run("--result", requested, submit_token=token)
        assert denied.returncode != 0 and "visible history" in denied.stderr
    assert judge.state.resolve_token(judge.token)["next_agent"] == 2


@pytest.mark.parametrize("failure", ["error", "missing_report", "not_found"])
def test_failed_result_reads_do_not_create_zero_score_cache_entries(judge, failure):
    assert judge.run().returncode == 0
    sid = accepted_id(judge)
    judge.cache.unlink()
    result = judge.state.submissions[sid]
    if failure == "error":
        result.update(status=judge_server.SubmissionStatus.ERROR, report=None,
                      error="synthetic grading failure")
    elif failure == "missing_report":
        result["report"] = None
    else:
        del judge.state.submissions[sid]
    recovered = judge.run("--result", sid)
    assert recovered.returncode != 0 and "ERROR:" in recovered.stderr
    assert "Score:" not in recovered.stdout and not judge.cache.exists()
    assert judge.state.resolve_token(judge.token)["next_agent"] == 2


@pytest.mark.parametrize("score,valid", [(0, True), (None, True), (7, False)])
def test_native_zero_missing_and_invalid_results_remain_distinct(judge, score, valid):
    assert judge.run().returncode == 0
    sid = accepted_id(judge)
    judge.cache.unlink()
    judge.state.submissions[sid]["report"].update(score=score, valid=valid)
    recovered = judge.run("--result", sid)
    assert recovered.returncode == 0
    cached = json.loads(judge.cache.read_text())
    assert cached["submissions"][0]["score"] == score
    assert cached["submissions"][0]["valid"] == valid
    if score is None:
        assert "Score:" not in recovered.stdout
    else:
        assert f"Score:       {score}" in recovered.stdout
    if not valid:
        assert "Valid:       no" in recovered.stdout and cached["best_pass_rate"] == 0


def test_details_alone_still_submits_and_obeys_existing_cooldown(judge):
    assert judge.run("--details").returncode == 0
    before = judge.state.resolve_token(judge.token)
    rejected = judge.run("--details")
    assert rejected.returncode != 0 and "cooldown" in rejected.stderr.lower()
    assert judge.state.resolve_token(judge.token) == before
